// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SupportFaceChat","status":true,"description":"Face Chat System / Skit System","parameters":{"x":"0","y":"550","width":"410","type":"1","IconNumber":"4","[C]color":"2","MsgWindowHeight":"","ChangeTone":"true"}}
];
